CREATE TABLE IF NOT EXISTS option_evaluation_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(64) NOT NULL,
    mode VARCHAR(16) NOT NULL DEFAULT 'single',
    user_id BIGINT UNSIGNED NULL,
    market VARCHAR(8) NULL,
    code VARCHAR(32) NULL,
    risk_profile VARCHAR(32) NOT NULL,
    request_json JSON NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'running',
    warnings_json JSON NULL,
    data_quality_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    finished_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_option_eval_run_id (run_id),
    KEY idx_option_eval_user (user_id, created_at),
    KEY idx_option_eval_code (market, code, created_at),
    KEY idx_option_eval_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权实验室评估任务';

CREATE TABLE IF NOT EXISTS option_evaluation_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(64) NOT NULL,
    market VARCHAR(8) NOT NULL,
    code VARCHAR(32) NOT NULL,
    name VARCHAR(255) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'running',
    best_strategy_json JSON NULL,
    data_quality_json JSON NULL,
    error_message TEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_option_eval_item_run (run_id),
    KEY idx_option_eval_item_code (market, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权实验室批量评估明细';

CREATE TABLE IF NOT EXISTS option_strategy_candidates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    candidate_id VARCHAR(64) NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    market VARCHAR(8) NOT NULL,
    code VARCHAR(32) NOT NULL,
    strategy_key VARCHAR(64) NOT NULL,
    strategy_name VARCHAR(128) NOT NULL,
    score DECIMAL(10,4) NOT NULL DEFAULT 0,
    recommendation_status VARCHAR(32) NOT NULL,
    fit_reason TEXT NULL,
    contract_details_json JSON NULL,
    risk_metrics_json JSON NULL,
    order_suggestion_json JSON NULL,
    warnings_json JSON NULL,
    data_quality_json JSON NULL,
    macro_fields_json JSON NULL COMMENT '宏观分析与综合评分展示字段',
    snapshot_id VARCHAR(64) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_option_candidate_id (candidate_id),
    KEY idx_option_candidate_run (run_id, score),
    KEY idx_option_candidate_code (market, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权策略候选';

CREATE TABLE IF NOT EXISTS option_macro_analysis_cache (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    cache_key VARCHAR(160) NOT NULL,
    market VARCHAR(8) NOT NULL,
    code VARCHAR(32) NOT NULL,
    analysis_profile VARCHAR(64) NOT NULL DEFAULT 'default',
    macro_score DECIMAL(10,4) NULL,
    macro_direction VARCHAR(32) NULL,
    news_impact VARCHAR(64) NULL,
    hot_sector_mark VARCHAR(64) NULL,
    main_force_risk_level VARCHAR(64) NULL,
    summary TEXT NULL,
    positive_factors_json JSON NULL,
    risk_factors_json JSON NULL,
    macro_factors_json JSON NULL,
    source_urls_json JSON NULL,
    warnings_json JSON NULL,
    provider VARCHAR(64) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at DATETIME(6) NULL,
    raw_payload_json JSON NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_option_macro_cache_key (cache_key),
    KEY idx_option_macro_cache_code (market, code, analysis_profile, created_at),
    KEY idx_option_macro_cache_expire (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权实验室宏观分析缓存';

CREATE TABLE IF NOT EXISTS option_order_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    plan_id VARCHAR(64) NOT NULL,
    candidate_id VARCHAR(64) NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'planned',
    contract_details_json JSON NULL,
    order_suggestion_json JSON NULL,
    risk_metrics_json JSON NULL,
    warnings_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_option_order_plan_id (plan_id),
    KEY idx_option_order_candidate (candidate_id),
    KEY idx_option_order_user (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权订单建议';

CREATE TABLE IF NOT EXISTS option_tracked_positions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    position_id VARCHAR(64) NOT NULL,
    plan_id VARCHAR(64) NULL,
    user_id BIGINT UNSIGNED NULL,
    market VARCHAR(8) NOT NULL,
    code VARCHAR(32) NOT NULL,
    strategy_name VARCHAR(128) NOT NULL,
    contract_details_json JSON NULL,
    filled_price DECIMAL(20,6) NULL,
    quantity INT NOT NULL DEFAULT 1,
    filled_at DATETIME(6) NULL,
    fee DECIMAL(20,6) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    current_state_json JSON NULL,
    current_action VARCHAR(128) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    closed_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_option_position_id (position_id),
    KEY idx_option_position_user (user_id, created_at),
    KEY idx_option_position_code (market, code, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权持仓监控';

CREATE TABLE IF NOT EXISTS option_monitor_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id VARCHAR(64) NOT NULL,
    position_id VARCHAR(64) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    message TEXT NOT NULL,
    snapshot_id VARCHAR(64) NULL,
    pushed_feishu TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_option_monitor_event_id (event_id),
    KEY idx_option_monitor_position (position_id, created_at),
    KEY idx_option_monitor_severity (severity, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权监控事件';

CREATE TABLE IF NOT EXISTS option_market_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    snapshot_id VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    market VARCHAR(8) NOT NULL,
    code VARCHAR(32) NOT NULL,
    underlying_json JSON NULL,
    option_chain_json JSON NULL,
    selected_quotes_json JSON NULL,
    data_quality_json JSON NULL,
    raw_payload_json JSON NULL,
    quote_time DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_option_snapshot_id (snapshot_id),
    KEY idx_option_snapshot_code (market, code, created_at),
    KEY idx_option_snapshot_provider (provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='期权行情快照';
